[0m10:06:53.474383 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D61E255220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D61EBD0DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D620B88EE0>]}


============================== 10:06:53.483383 | e11e34ce-ca00-4af3-85cb-665c44bd3b40 ==============================
[0m10:06:53.483383 [info ] [MainThread]: Running with dbt=1.8.2
[0m10:06:53.486382 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\kawal\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init stock_project', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:06:53.550866 [debug] [MainThread]: Starter project path: C:\Users\kawal\anaconda3\envs\stock_processor\lib\site-packages\dbt\include\starter_project
[0m10:06:53.604766 [info ] [MainThread]: 
Your new dbt project "stock_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:06:53.609365 [info ] [MainThread]: Setting up your profile.
[0m10:07:05.824463 [debug] [MainThread]: Command `dbt init` succeeded at 10:07:05.824463 after 12.53 seconds
[0m10:07:05.825464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D61E255220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D620D84610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D620BB7E80>]}
[0m10:07:05.826463 [debug] [MainThread]: Flushing usage events
[0m10:17:48.640407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D3300C52B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D32EF64400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D332724DF0>]}


============================== 10:17:48.647411 | 5cffff74-92cd-402b-bc05-ec424e78ab1a ==============================
[0m10:17:48.647411 [info ] [MainThread]: Running with dbt=1.8.2
[0m10:17:48.649407 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\kawal\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:17:48.650452 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\kawal\OneDrive\Desktop\Python Projects\real-time-stock-processor\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:17:48.654410 [debug] [MainThread]: Command `dbt run` failed at 10:17:48.654410 after 0.15 seconds
[0m10:17:48.655485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D3300C52B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D332724DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D3309EAFA0>]}
[0m10:17:48.656536 [debug] [MainThread]: Flushing usage events
[0m12:35:20.877281 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA63D7220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA8B47A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA6C09790>]}


============================== 12:35:20.883283 | 49bd52b9-1ebb-4e84-8309-b8b838bb939f ==============================
[0m12:35:20.883283 [info ] [MainThread]: Running with dbt=1.8.2
[0m12:35:20.885283 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\kawal\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:35:20.886280 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\kawal\OneDrive\Desktop\Python Projects\real-time-stock-processor\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:35:20.891292 [debug] [MainThread]: Command `dbt run` failed at 12:35:20.890289 after 0.16 seconds
[0m12:35:20.892284 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA63D7220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA6D3EDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA6C09790>]}
[0m12:35:20.893285 [debug] [MainThread]: Flushing usage events
